import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* 2. Đặt Navbar ở ĐÂY (phía trên children) */}
        <Navbar /> 

        {/* 3. children chính là nội dung thay đổi của từng trang (Home, Courses, Detail...) */}
        <main>
            {children}
        </main>
        
        {/* Bạn cũng có thể đặt Footer ở dưới này nếu muốn nó hiện ở mọi trang */}
      </body>
    </html>
  );
}
